[workspace]
members = [
    "crates/vantage-core",
    "crates/vantage-pek",
    "crates/vantage-tx",
    "crates/vantage-runtime",
    "crates/vantage-trust",
    "crates/vantage-daemon",
    "crates/vantage-prn",
    "crates/vantage-client",
    "crates/vantage-vfp",
    "crates/vantage-metrics",
    "crates/vantage-benchmark",
    "app/src-tauri"
]
resolver = "2"
